// POST: http://localhost:4000/api/auth/
// Generated by https://quicktype.io
export interface LoginResponse {
  ok:    boolean;
  uid:   string;
  name:  string;
  token: string;
  msg?: string;
}

// GET: http://localhost:4000/api/auth/renew
// Generated by https://quicktype.io

export interface RevalidateTokenResponse {
  ok:    boolean;
  uid:   string;
  name:  string;
  token: string;
}

