

// POST: {{url-react}}/api/events
// Generated by https://quicktype.io

export interface CreateEventResponse {
  ok:     boolean;
  evento: Evento;
}

export interface Evento {
  title: string;
  notes: string;
  start: string;
  end:   string;
  user:  string;
  id:    string;
}


// GET: http://localhost:4000/api/events
// Generated by https://quicktype.io

export interface GetEventsResponse {
  ok:      boolean;
  msg:     string;
  eventos: EventoGetEvents[];
}

export interface EventoGetEvents {
  title: string;
  notes: string;
  start: string;
  end:   string;
  user:  UserGetEvents;
  id:    string;
}

export interface UserGetEvents {
  _id:  string;
  name: string;
}

