

// POST: {{url-react}}/api/events
// Generated by https://quicktype.io

export interface CreateEventResponse {
  ok:     boolean;
  evento: Evento;
}

export interface Evento {
  title: string;
  notes: string;
  start: string;
  end:   string;
  user:  string;
  id:    string;
}
